import streamlit as st
import requests
from PIL import Image, ImageDraw, ImageFont
from io import BytesIO
import textwrap
import json

OLLAMA_URL = "http://localhost:11434"
LLM_MODEL = "mistral"

def call_ollama_chat(messages, model=LLM_MODEL):
    url = f"{OLLAMA_URL}/api/chat"
    payload = {"model": model, "messages": messages}
    try:
        resp = requests.post(url, json=payload, timeout=30)
        resp.raise_for_status()
        # Parse streaming response JSON to extract content
        lines = resp.text.strip().splitlines()
        content = ""
        for line in lines:
            try:
                data = json.loads(line)
                if "message" in data and "content" in data["message"]:
                    content += data["message"]["content"]
            except:
                continue
        return content.strip()
    except Exception as e:
        raise RuntimeError(f"Ollama error: {e}") from e

def parse_product_idea(idea_text):
    prompt = f"Extract product info from this idea in readable text:\n{idea_text}"
    messages = [{"role": "user", "content": prompt}]
    return call_ollama_chat(messages)

def generate_product_texts(idea_text):
    prompt = f"Write product name, 2-3 sentence description, 5 features, 5-word tagline for:\n{idea_text}"
    messages = [{"role": "user", "content": prompt}]
    return call_ollama_chat(messages)

def generate_mockup_image(product_name, design_style, suggested_colors, idea_text, width=1024, height=768):
    bg = (245,245,250)
    fg = (30,30,30)
    accent = (30,120,210)
    img = Image.new("RGB", (width,height), bg)
    d = ImageDraw.Draw(img)
    try:
        font_title = ImageFont.truetype("arial.ttf",48)
        font_sub = ImageFont.truetype("arial.ttf",24)
        font_body = ImageFont.truetype("arial.ttf",20)
    except:
        font_title = ImageFont.load_default()
        font_sub = ImageFont.load_default()
        font_body = ImageFont.load_default()

    margin = 40
    box_x0, box_y0 = margin, margin+20
    box_x1, box_y1 = width-margin, int(height*0.62)
    d.rectangle([box_x0, box_y0, box_x1, box_y1], fill=(255,255,255), outline=(220,220,220))

    center_x = (box_x0+box_x1)//2
    center_y = (box_y0+box_y1)//2
    shape_w, shape_h = int((box_x1-box_x0)*0.35), int((box_y1-box_y0)*0.45)
    shape_x0, shape_y0 = center_x-shape_w//2, center_y-shape_h//2
    shape_x1, shape_y1 = center_x+shape_w//2, center_y+shape_h//2
    d.rounded_rectangle([shape_x0,shape_y0,shape_x1,shape_y1], radius=30, outline=accent, width=6)
    d.ellipse([shape_x1-30,center_y-10,shape_x1-10,center_y+10], fill=accent)

    title = product_name
    subtitle = f"Style: {design_style} • Colors: {suggested_colors}"
    wrapped_idea = "\n".join(textwrap.wrap(idea_text, width=80))
    d.text((margin+10,12), title, fill=fg, font=font_title)
    d.text((margin+10,67), subtitle, fill=(90,90,90), font=font_sub)
    d.text((margin+10,box_y1+10),"Idea:",fill=fg,font=font_sub)
    d.text((margin+10,box_y1+40),wrapped_idea,fill=(60,60,60),font=font_body)
    d.rectangle([width-260,height-80,width-40,height-30], fill=accent)
    d.text((width-250,height-72),"Concept generated by ProdGenAI", fill=(255,255,255), font=font_body)

    return img

st.set_page_config(page_title="ProdGenAI", layout="centered")
st.title("ProdGenAI — Product Design Generator")

with st.form(key="idea_form"):
    idea = st.text_area("Enter your product idea:")
    submit = st.form_submit_button("Generate")

if submit:
    if not idea.strip():
        st.error("Enter a product idea.")
        st.stop()

    try:
        parsed_text = parse_product_idea(idea)
        st.subheader("Parsed Info")
        st.text(parsed_text)
    except Exception as e:
        st.error(f"Parse error: {e}")
        st.stop()

    try:
        product_texts = generate_product_texts(idea)
        st.subheader("Product Details")
        st.text(product_texts)
    except Exception as e:
        st.error(f"Generation error: {e}")
        st.stop()

    lines = [l.strip() for l in product_texts.splitlines() if l.strip()]
    product_name = lines[0] if lines else "Product Concept"
    design_style = "minimalist"
    suggested_colors = "blue, white"

    img = generate_mockup_image(product_name, design_style, suggested_colors, idea)
    buf = BytesIO()
    img.save(buf, format="PNG")
    st.image(buf.getvalue(), use_column_width=True)
    st.download_button("Download Image", data=buf.getvalue(), file_name="concept.png", mime="image/png")
